### ISSUE TITLE
Migrate documentation to github

### ISSUE THREAD

**Issue by bspaans** [bspaans/python-mingus#1]
As a maintainer I want to move the documentation that is being served at https://code.google.com/p/mingus/wiki/mingusIndex?tm=6 to be available through github.

A/C:
* I can access and browse the documentation through github

**Comment by mutil** [comment]
Will this happen any time soon? Or, at least, can you describe how can one generate the documentation from doc/wiki folder locally? The link to https://code.google.com/p/mingus/wiki/ now redirects to the github repository so there is no access to the former google wiki.

Thanks for your effort, @bspaans

**Comment by bspaans** [comment]
Hi @mutil, thanks for your message. This issue is currently the highest priority for me but will probably involve a lot of changes. Most of the docstrings are in Google's old wiki format, because I was lazy, so I want to take the opportunity to address that, go through it all and move to something more standard like Sphinx. 

As for having a local copy, you can try the scripts/generate_wiki_docs.py script, but your mileage may vary. Sorry for the inconvenience; I'm gonna try and get the new documentation online ASAP.

**Comment by bspaans** [comment]
Done!

http://bspaans.github.io/python-mingus/

**Comment by mutil** [comment]
That was fast! Thank you.
