### ISSUE TITLE
Possible error

### ISSUE THREAD

**Issue by dpawson** [bspaans/python-mingus#16]
http://bspaans.github.io/python-mingus/doc/wiki/tutorialChords.html

Running
def chord_7(note, key):
    return chords.seventh(note,key)

print("Eb 7 ", chord_7('Eb','C'))

I see ('Eb 7 ', ['Eb', 'G', 'B', 'D'])

I think it should be Eb G Bb D
which is confirmed by other sites.

I may be wrong.

**Comment by bspaans** [comment]
This is because both Eb and Bb are not in the key of C, so instead mingus treats Eb as a diminished E and builds the chord like it would if it were an E. Try changing the key to 'Eb' and it should work.

**Comment by dpawson** [comment]
Thanks Bart. I confess I don't understand that.
I'll do some more reading - sorry to waste your time.

regards Dave P

On 8 September 2015 at 18:40, Bart Spaans <notifications@github.com> wrote:

> This is because both Eb and Bb are not in the key of C, so instead mingus
> treats Eb as a diminished E and builds the chord like it would if it were
> an E. Try changing the key to 'Eb' and it should work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bspaans/python-mingus/issues/16#issuecomment-138644739>
> .
>



-- 
Dave Pawson
XSLT XSL-FO FAQ.
Docbook FAQ.
http://www.dpawson.co.uk

**Comment by dpawson** [comment]
Bart, I'm having issues running on Python 3?
 File "/usr/lib/python3.4/site-packages/mingus/core/notes.py", line 29, in
<module>
    from mt_exceptions import NoteFormatError, RangeError, FormatError
ImportError: No module named 'mt_exceptions'

Any suggestions please?

regards

On 8 September 2015 at 18:40, Bart Spaans <notifications@github.com> wrote:

> This is because both Eb and Bb are not in the key of C, so instead mingus
> treats Eb as a diminished E and builds the chord like it would if it were
> an E. Try changing the key to 'Eb' and it should work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bspaans/python-mingus/issues/16#issuecomment-138644739>
> .
>



-- 
Dave Pawson
XSLT XSL-FO FAQ.
Docbook FAQ.
http://www.dpawson.co.uk

**Comment by dpawson** [comment]
http://bspaans.github.io/python-mingus/doc/wiki/tutorialNote.html

has

Minor and Major conversions

Minor:

>>> notes.to_minor("C")
"A"
>>> notes.to_minor("F")

Using

>>> import mingus.core.notes as notes

$ python
Python 2.7.10 (default, Jul  5 2015, 14:15:43)
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mingus.core.notes as notes
>>> print notes.to_minor('A')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'to_minor'
>>> dir(notes)
['FormatError', 'NoteFormatError', 'RangeError', '__builtins__',
'__doc__', '__file__', '__name__', '__package__', '_note_dict',
'augment', 'diminish', 'fifths', 'int_to_note', 'is_enharmonic',
'is_valid_note', 'note_to_int', 'reduce_accidentals',
'remove_redundant_accidentals']

I.e. no 'to_minor() attribute?

regards

-- 
Dave Pawson
XSLT XSL-FO FAQ.
Docbook FAQ.
http://www.dpawson.co.uk
