### ISSUE TITLE
Python 3 install?

### ISSUE THREAD

**Issue by dpawson** [bspaans/python-mingus#17]
>pip3 install mingus

Collecting mingus
  Using cached mingus-0.5.1.tar.gz
Installing collected packages: mingus
  Running setup.py install for mingus
Successfully installed mingus-0.5.1

Tried to run a program using mingus.

$ python3 chords2.py
Traceback (most recent call last):
  File "chords2.py", line 4, in <module>
    import mingus.core.notes as notes
  File "/usr/lib/python3.4/site-packages/mingus/core/notes.py", line 29, in <module>
    from mt_exceptions import NoteFormatError, RangeError, FormatError
ImportError: No module named 'mt_exceptions'

Is this a mingus module please?

**Comment by kevin-brown** [comment]
We were just testing out mingus and noticed that it uses the relative imports, so it definitely isn't compatible with Python 3.

**Comment by bspaans** [comment]
Indeed, Python3 is not supported at the moment, but will probably be part of the 0.6 release.
