### ISSUE TITLE
Porting to Python 3?

### ISSUE THREAD

**Issue by urbster1** [bspaans/python-mingus#45]
It would be really great if this could be ported to Python 3...

**Comment by edudobay** [comment]
I have made most of the modifications needed to run under Python 3… you can check my fork: https://github.com/edudobay/python-mingus

Unfortunately I haven't had time to take care of it, but I think it's already usable.

**Comment by urbster1** [comment]
thanks!!

**Comment by edudobay** [comment]
Changes have been merged to master.
