### ISSUE TITLE
Sequencer.stop_NoteContainer() sends the wrong notification

### ISSUE THREAD

**Issue by reticulatus** [bspaans/python-mingus#60]
In sequencer.py the method stop_NoteContainer() sends the notification self.MSG_PLAY_NC.

Should it not be sending self.MSG_STOP_NC instead?

I am using mingus 0.6.0 + Python 3.6.9 + Linux Mint 19.3.

**Comment by edudobay** [comment]
Seems you're right. Thank you again! I'm fixing this on `master` and will make it for the next release.
