### ISSUE TITLE
Note volume not working

### ISSUE THREAD

**Issue by allexandre97** [bspaans/python-mingus#61]
Hello!

I am trying to write some midi files with mingus, but the volume assignation seems to not be working. I am using the method note = [[res[i][0],{'volume':res[i][2]}]] where res[i][0] is a string which dictates the note and res[i][2] is an integer. Is this a known issue or maybe I am doing something wrong? 

Thanks in advance :)

**Comment by edudobay** [comment]
Hi! I'm trying to understand this part of the library code. It seems indeed this is not correctly implemented. Could you share some more of the code you're using to help testing and fixing it?

**Comment by reticulatus** [comment]
The problem I have with trying to set a Note's velocity and channel using the 'dynamics' argument is that it just gets assigned to the instance attribute self.dynamics and is not used to initialise the Note instance's velocity and channel attributes.

However, the Note class does have class attributes: Note.velocity = 64 and Note.channel = 1. 

When Sequencer.play_Note() is called, it then uses those class attributes and doesn't use the values in the dynamics attribute or the args passed to play_Note().

The only way I have found for play_Note() to use the values in a Note object is to explicitly assign values to the object's instance attributes after it has been created. As a workaround, I use the following function:

```
def createNote(name, octave=4, channel=1, velocity=100):
    note = Note(name, octave)
    note.channel = channel
    note.velocity = velocity
    return note

```

**Comment by edudobay** [comment]
This is fixed now on master. The `dynamics` attribute is deprecated and internal workings of the Note class now make it possible to specify channel/velocity either directly or via dynamics:

```python
n = Note("A", 4, channel=1, velocity=100)
n = Note("A", 4, {"channel": 1, "velocity": 100})  # same thing but uglier
```

**Comment by edudobay** [comment]
Note: The `volume` property doesn't exist – it was typed incorrectly in one example.

**Comment by allexandre97** [comment]
Perfect! This solved the problem, thank you very much!
