### ISSUE TITLE
midi_file_in.py - python3 compatibility problems

### ISSUE THREAD

**Issue by reticulatus** [bspaans/python-mingus#64]
This is a follow-up to Issue #58 "midi_file_in.py opens midi file in text mode".

After testing the changes made in the main branch, I have found the following problems.

Lines 221 & 222 use the single slash division operator. 

In Python3 this returns a float which causes fp.read() to raise: 

`TypeError: 'float' object cannot be interpreted as an integer`

Changing the statements to use the double slash division operator allows the code to continue.

However, when it reaches line 148:

`thirtyseconds = self.bytes_to_int(d[3])`

this calls line 226:

`return int(binascii.b2a_hex(bytes), 16)`

which raises:

`TypeError: a bytes-like object is required, not 'int'`

By now I was coming to the conclusion that midi_file_in.py has not been updated for python3. There may be other compatibility problems after this.

I have found an alternative way to save and load track information in my project, which doesn't use midi files, so I have not investigated this problem further.

**Comment by edudobay** [comment]
Thanks for your feedback. I'm fixing these other issues now. Indeed they weren't 100% ready for Python 3 — they weren't caught by automated migration tools and there are no automated tests for MIDI funcionality :(

**Comment by edudobay** [comment]
@reticulatus I've successfully ran the example code in the `midi_file_in` module. The changes are already in the master branch. Could you please check if your problems are solved now?

**Comment by reticulatus** [comment]
Thank you @edudobay - I've run my code using the version from the master branch and it now works without throwing any exceptions. 

The values in the data I read back from the midi file are the same as those that were written to the file, except all the duration values are shown as floats, not integers.

e.g. part of the original data: [0.0, 8, ['C-5', 'E-5', 'G-5']]
the same part of the output from midi_file_in.py: [0.0, 8.0, ['C-5', 'E-5', 'G-5']]

However, the version read back from the midi file does play OK and sounds the same as the original sequence.

**Comment by edudobay** [comment]
Great! I'm not sure about how it was designed, but it seems reasonable that the values read from the file are always normalized as floats. In the future I'd like to take a closer look at those types because there are some inconsistencies here and there. But glad to know your issue's solved!

**Comment by edudobay** [comment]
Hi @jkeesh! Sorry for the delay. I hadn't made a tagged release for the fix, so if you installed it with `pip install mingus` you wouldn't get the latest changes. Now you can upgrade to 0.6.1 with `pip install -U mingus`.
