### ISSUE TITLE
Not working with fluidsynth 2

### ISSUE THREAD

**Issue by TomPJWyatt** [bspaans/python-mingus#73]
Hello and thanks for the great package!

I was getting: ImportError("Couldn't find the FluidSynth library.")

I think it was because I have fluidsynth 2 installed and mingus isn't yet compatible.

Things seem to work when I tweak pyfluidsynth by adding find_library("libfluidsynth-2") into the ctype.utils search...

**Comment by edudobay** [comment]
Hi @TomPJWyatt, I guess this happens under Windows - is that correct?

There is an open PR which I hope to merge in the next few days, it should fix this. https://github.com/bspaans/python-mingus/pull/82

**Comment by TomPJWyatt** [comment]
Hi, yes it was Windows. Ok that sounds good!
